![logo](img/logoitqv1.jpg)
<br>
# 0.2 Programa2.Estandarizacion
<br>

![python](img/python_logo.png)

<br>

*Kenin CUsme*

<br>

https://github.com/kenin395/Machine-Learning_2.git

In [5]:
from sklearn import preprocessing
import numpy as np

In [6]:
# Carga de datos.
X_train = np.array([[ 1., -1., 2.],
                    [ 2., 0., 0.],
                    [ 0., 1., -1.]])

In [7]:
# Limpieza de datos: estandarización.
standardizer = preprocessing.StandardScaler()

# Estandarizamos los datos de entrenamiento
X_train_std=standardizer.fit_transform(X_train)
print(X_train_std)

[[ 0.         -1.22474487  1.33630621]
 [ 1.22474487  0.         -0.26726124]
 [-1.22474487  1.22474487 -1.06904497]]


In [8]:
X_train_2 = np.array([[ 1., -1., 2.],
                      [ 2., 0., 0.],
                      [ 0., 1., -1.]])

In [9]:
# Aplicamos los métodos "fit" y "transform" por separado
f=preprocessing.StandardScaler()
f=f.fit(X_train)
X_train_2_std = f.transform(X_train_2)
print(X_train_2_std)
# ???

[[ 0.         -1.22474487  1.33630621]
 [ 1.22474487  0.         -0.26726124]
 [-1.22474487  1.22474487 -1.06904497]]


In [10]:
# Aplicamos los métodos "fit" y "transform" por separado
f = preprocessing.StandardScaler()
f = f.fit(X_train)

X_train_2_std = f.transform(X_train_2)

print(X_train_2_std)

# Comprobar si las matrices estandarizadas son iguales
print(np.array_equiv(X_train_std, X_train_2_std))

[[ 0.         -1.22474487  1.33630621]
 [ 1.22474487  0.         -0.26726124]
 [-1.22474487  1.22474487 -1.06904497]]
True
